# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 2 * * 1' # At 02:00 on Monday

name: CI
jobs:
  test:
    timeout-minutes: 5
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        node: [8, 10, 12, 14, 16, 17]
        include:
          - os: macos-latest
            node: 16
          - os: windows-latest
            node: 16
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm run --ignore-scripts test
  code-lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci --ignnore-scripts
      - name: Code lint
        run: npm run --ignore-scripts lint
